### ISSUE TITLE
Does not respond to reportLocation

### ISSUE THREAD

**Issue by tnemrap** [owntracks/ios#377]
When i publish 
`{"_type":"cmd","action":"reportLocation"}`
my IOS does not respond.

My Android devices does respond.

**Comment by jpmens** [comment]
If the app is in the background it cannot respond immediately; iOS puts apps to sleep and wakes them up periodically. Try publiishing that request with `qos=2` for ensured delivery, and I think you should see a response within several minutes. Also please double-check the topic name you are publishing to (i.e. `owntracks/user/device/cmd`

**Comment by ckrey** [comment]
@tnemrap does this answer your question?

**Comment by tnemrap** [comment]
No the qos setting does no difference. I have to put it in foreground then it answers on the request.

**Comment by ckrey** [comment]
Correct, the app does respond when in foreground or when it is woken up by iOS eventually. This usually happens every 15min for a short tim if the battery level is > 20%.

**Comment by arsaboo** [comment]
I am using the following automation in Home Assistant to force update and it is not working for me:
```yaml
  action:
    - service: mqtt.publish
      data:
        topic: "owntracks/pi/device/cmd"
        payload_template: '{"_type": "cmd","action": "reportLocation", "batt": %BATT}'
```
How, do I modify it to add `qos=2`? Thanks!
