### ISSUE TITLE
iBeacon Detection No Longer Working (iOS)

### ISSUE THREAD

**Issue by grantalewis** [owntracks/ios#702]
I've recently begun experiencing problems with a long-standing OwnTracks/iBeacons config. I suspect something has changed with how iOS allows OwnTracks to use Bluetooth but am not certain. The description below applies to my iPhone 13, but I believe it's affecting all phones in the household (two iPhone 13s and two iPhone XSs).

Former/expected behavior (MQTT and Home Assistant): For years I have used OwnTracks and six RadBeacon USB to identify close proximity to the house. For example, if a family member is detected recently "home" and their phone pings the front door iBeacon when the door is locked, it unlocks. Although I haven't made changes, those automations have stopped working in the last 60-90 days.

I have the most recent iOS and Owntracks. I've tried deleting OwnTracks and manually re-entering settings, restoring waypoints from an .otrw backup. No luck.

All iBeacons use the same UUID; each uses a different major/minor. Radius for each region is set to 0. OwnTracks reports that it's connected to the MQTT server. 

I've got a bit of yaml in Home Assistant that I use for troubleshooting:

```
  - alias: Front Door iBeacon Notification - ON
    initial_state: true
    trigger:
      platform: mqtt
      topic: "owntracks/+/+/event"
    condition: 
      condition: and
      conditions:
      - condition: template
        value_template: "{{ 'front_door' in trigger.payload }}"
      - condition: template
        value_template: "{{ 'enter' in trigger.payload }}"
    action:
      - service: notify.mobile_app_my_iphone
        data:
          message: "Front Door iBeacon ON."
```
There's additional yaml for each of the other five beacons.

Current behavior: I approach an iBeacon with my phone and watch Regions in OwnTracks. Prior behavior was a fairly quick response; now, nothing at all happens. If I then launch the RadBeacon config tool on my phone, OwnTracks nearly immediately detects the beacons. And if I have the above yaml automations enabled while launching the RadBeacon config tool, I receive the notifications as expected.

I'm happy to provide more information or conduct additional troubleshooting steps.
