### ISSUE TITLE
Question: please help to import zones from Home Assistant

### ISSUE THREAD

**Issue by jbrepogmailcom** [owntracks/ios#805]
Hello. Instead of OwnTracks to detect position once a while and report it to Home Assistant to check in/out of zone. I would like to import HA zones to OwnTracks on iOS and have the iOS handle entries and exits. I looked at booklet and there is some json structured command to import zones.

Is there easier way to import zones from HA to OwnTracks over mqtt? I tried advice like adding following to HA's configuration.yaml, but it did not work:
```
owntracks:
  waypoints: true
  waypoint_whitelist:
    - janb
```

Would you have any advice please?
